language: go

sudo: required
dist: trusty

go:
  - 1.9.x
  - 1.10.x
  - master
  - tip

env:
  - LIBVIPS=8.5.9
  - LIBVIPS=8.6.3

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache:
  apt:
  directories:
    - $HOME/libvips

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev

before_install:
  - wget https://github.com/jcupitt/libvips/archive/v$LIBVIPS.zip
  - unzip v$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    --prefix=$HOME/libvips
    $1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - export PATH=$PATH:$HOME/libvips/bin
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/libvips/lib/pkgconfig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/libvips/lib
  - vips --vips-version

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make cover

after_success:
  - goveralls -coverprofile=./coverage/test.cov -service=travis-ci

#deploy:
#  on:
#    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
