language: go

sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - master
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - add-apt-repository ppa:masterminds/glide
  - apt-get update
  - apt-get install glide
  - glide install

script:
  - make travis
  - goveralls -service=travis-ci

#deploy:
#  on:
#    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
