language: go

sudo: required
dist: trusty

go:
  - 1.7
  - 1.8
  - master
  - tip

env:
  - LIBVIPS=8.2.2
  - LIBVIPS=8.3.0
  - LIBVIPS=8.4.2
  - LIBVIPS=8.5.3
  - LIBVIPS=master

matrix:
  allow_failures:
    - go: master
    - go: tip
    - env: LIBVIPS=8.2.2
    - env: LIBVIPS=8.3.0
    - env: LIBVIPS=master

cache: apt

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev

before_install:
  - wget https://github.com/jcupitt/libvips/archive/v$LIBVIPS.zip
  - unzip libvips-$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    $1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/Masterminds/glide
  - glide install

script:
  - make travis
  - goveralls -service=travis-ci

#deploy:
#  on:
#    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
